config/routes.rb
Oleksa::Application.routes.draw do

  scope '(:locale)' do
    devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
    resources :pages
    resources :languages
    resources :periods
    resources :contents
    resources :content_types
    resources :nodes
  end

end

app/models/node.rb
class Node < ActiveRecord::Base
  attr_accessible :name, :content_type, :title, :content
  validates :name, presence: true, uniqueness: true
  belongs_to :content_type
  has_many :children, class_name: 'Node', foreign_key: 'parent_id'
  belongs_to :parent, class_name: 'Node'
  translates :title, :content
#  has_and_belongs_to_many :tags, class_name: 'Node'
end

app/models/node_type.rb
class NodeType < ActiveRecord::Base
  attr_accessible :name
  has_many :nodes, :dependent => :nullify
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @nodes }
    end
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
    @node = Node.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @node }
      format.js
    end
  end

  # GET /nodes/new
  # GET /nodes/new.json
  def new
    @node = Node.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @node }
    end
  end

  # GET /nodes/1/edit
  def edit
    @node = Node.find(params[:id])
    @languages = Language.all;
    respond_to do |format|
#      format.html
      format.js
    end
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(params[:node])

    respond_to do |format|
      if @node.save
        format.html { redirect_to @node, notice: 'Node was successfully created.' }
        format.json { render json: @node, status: :created, location: @node }
      else
        format.html { render action: "new" }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  # PUT /nodes/1
  # PUT /nodes/1.json
  def update
    @node = Node.find(params[:id])

    respond_to do |format|
      if @node.update_attributes(params[:node])
        format.html { redirect_to @node, notice: 'Node was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node = Node.find(params[:id])
    @node.destroy

    respond_to do |format|
      format.html { redirect_to nodes_url }
      format.json { head :no_content }
      format.js
    end
  end
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/nodes/_form.html.erb
<%= form_for(@node, remote: true) do |f| %>
  <ul class="locale">
  <% @languages.each do |language| %>
    <li><%= link_to_unless_current language.ident, edit_node_path(@node, locale: language.ident), remote: true %></li>
  <% end %>
  </ul>

  <% if @node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@node.errors.count, "error") %> prohibited this node from being saved:</h2>
      <ul>
      <% @node.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %><br />
    <%= f.text_field :title %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nodes/_node.html.erb
<li id="node_<%= node.id %>">
  <div class="title"><%= link_to node.name, node %> : <%= node.title %></div>
  <div class="locales">
    <ul>
    <% node.translations.each do |t| %>
        <li><%= link_to t.locale, edit_node_path(node, locale: t.locale), remote: true %></li>
    <% end %>
    </ul>
    <div></div>
  </div>
  <div class="actions">
    <%= link_to 'Show', node %>
    <%= link_to 'Edit', edit_node_path(node), remote: true %>
    <%= link_to 'Destroy', node, method: :delete, remote: true %>
  </div>
</li>

app/views/nodes/create.js.erb
var errors_div = $('#node-create-form .errors');
<% if @node.new_record? %>
    $("input#node_name").effect('highlight', {color:'red'});
  errors_div.html('<ul><% @node.errors.full_messages.each do |msg| %><li><%= escape_javascript(msg) %></li><% end %></ul>');
<% else %>
  $('ul#nodes').append("<%= escape_javascript(render @node) %>")
  errors_div.html('');
  $('li#<%= dom_id(@node) %>').effect('highlight');
<% end %>

app/views/nodes/destroy.js.erb
$('#<%= dom_id(@node) %>').fadeOut();

app/views/nodes/edit.html.erb
<h1>Editing node</h1>

<%= render 'form' %>

<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/edit.js.erb
$('#edit_node_dialog').dialog({title: '<%= escape_javascript @node.title %>', width: 600}).html('<%= escape_javascript render 'form' %>');

app/views/nodes/index.html.erb
<h1>Listing nodes</h1>

<div id="edit_node_dialog"></div>

<ul id="nodes">
    <%= render @nodes %>
</ul>

<br />


<%= form_for(Node.new, remote: true) do |f| %>
  <div id="node-create-form">
    <div class="errors"></div>
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

<%= link_to 'New Node', new_node_path %>

app/views/nodes/new.html.erb
<h1>New node</h1>

<%= render 'form' %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @node.name %>
</p>


<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/update.js.erb
$('#edit_node_dialog').dialog("close");
$('#node_<%= @node.id %>').replaceWith("<%= escape_javascript( render @node ) %>");